version: "3.5"

services:
  ms-sql:
    build:
      context: .
      dockerfile: ./Dockerfile-Db
    container_name: ms-sql
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    ports:
      - "1400:1433"
    networks:
      - network

networks:
  network:
    name: network
        