version: "3.5"

services:
  api:
    build:
      context: .
      dockerfile: ./src/ContainerManager.API/Dockerfile
    container_name: containers-manager-api
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:55100
      - "CONFIG_ConnectionStrings:ContainersManagerDBConnectionString=Server=ms-sql;database=ContainersManagerDB;uid=sa;pwd=Password123"
    ports:
      - "55100:55100"
    depends_on:
      - ms-sql     
    networks:
      - network 
      
networks:
  network:
    name: network
        